name: Build and Push Docker Image

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build . -t ghcr.io/drinbol/action_test:latest

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push Docker image to GitHub Packages
      run: docker push ghcr.io/drinbol/action_test:latest

    - name: Set package visibility to public
      run: |
        curl \
          -X PATCH \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/user/packages/container/action_test/visibility \
          -d '{"visibility":"public"}'
